// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProvisionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MinecraftVersion string                 `protobuf:"bytes,2,opt,name=minecraftVersion,proto3" json:"minecraftVersion,omitempty"`
	Plugins          []*Plugin              `protobuf:"bytes,3,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProvisionRequest) GetMinecraftVersion() string {
	if x != nil {
		return x.MinecraftVersion
	}
	return ""
}

func (x *ProvisionRequest) GetPlugins() []*Plugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type ProvisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionResponse) Reset() {
	*x = ProvisionResponse{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionResponse) ProtoMessage() {}

func (x *ProvisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionResponse.ProtoReflect.Descriptor instead.
func (*ProvisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ProvisionResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ProvisionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerActionRequest) Reset() {
	*x = ServerActionRequest{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerActionRequest) ProtoMessage() {}

func (x *ServerActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerActionRequest.ProtoReflect.Descriptor instead.
func (*ServerActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ServerActionRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type ServerActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerActionResponse) Reset() {
	*x = ServerActionResponse{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerActionResponse) ProtoMessage() {}

func (x *ServerActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerActionResponse.ProtoReflect.Descriptor instead.
func (*ServerActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ServerActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdatePluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Plugins       []*Plugin              `protobuf:"bytes,2,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePluginsRequest) Reset() {
	*x = UpdatePluginsRequest{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePluginsRequest) ProtoMessage() {}

func (x *UpdatePluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePluginsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePluginsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePluginsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *UpdatePluginsRequest) GetPlugins() []*Plugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type UpdatePluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePluginsResponse) Reset() {
	*x = UpdatePluginsResponse{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePluginsResponse) ProtoMessage() {}

func (x *UpdatePluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePluginsResponse.ProtoReflect.Descriptor instead.
func (*UpdatePluginsResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePluginsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusResponse) Reset() {
	*x = ServerStatusResponse{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusResponse) ProtoMessage() {}

func (x *ServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusResponse.ProtoReflect.Descriptor instead.
func (*ServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ServerStatusResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ServerStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServerStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Plugin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugin.ProtoReflect.Descriptor instead.
func (*Plugin) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Plugin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plugin) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,4,opt,name=memoryBytes,proto3" json:"memoryBytes,omitempty"`
	CpuCores      int32                  `protobuf:"varint,5,opt,name=cpuCores,proto3" json:"cpuCores,omitempty"`
	IpAddress     string                 `protobuf:"bytes,6,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterNodeRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterNodeRequest) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *RegisterNodeRequest) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *RegisterNodeRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Servers       []*ServerStatus        `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	Metrics       *SystemMetrics         `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetServers() []*ServerStatus {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *HeartbeatRequest) GetMetrics() *SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PlayerCount   int32                  `protobuf:"varint,3,opt,name=playerCount,proto3" json:"playerCount,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,4,opt,name=cpuUsage,proto3" json:"cpuUsage,omitempty"`
	MemoryUsage   int64                  `protobuf:"varint,5,opt,name=memoryUsage,proto3" json:"memoryUsage,omitempty"`
	Uptime        int64                  `protobuf:"varint,6,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ServerStatus) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ServerStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServerStatus) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *ServerStatus) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ServerStatus) GetMemoryUsage() int64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ServerStatus) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type SystemMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage        float32                `protobuf:"fixed32,1,opt,name=cpuUsage,proto3" json:"cpuUsage,omitempty"`
	MemoryUsed      int64                  `protobuf:"varint,2,opt,name=memoryUsed,proto3" json:"memoryUsed,omitempty"`
	MemoryTotal     int64                  `protobuf:"varint,3,opt,name=memoryTotal,proto3" json:"memoryTotal,omitempty"`
	DiskUsage       float32                `protobuf:"fixed32,4,opt,name=diskUsage,proto3" json:"diskUsage,omitempty"`
	NetworkBytesIn  int64                  `protobuf:"varint,5,opt,name=networkBytesIn,proto3" json:"networkBytesIn,omitempty"`
	NetworkBytesOut int64                  `protobuf:"varint,6,opt,name=networkBytesOut,proto3" json:"networkBytesOut,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *SystemMetrics) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *SystemMetrics) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *SystemMetrics) GetDiskUsage() float32 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *SystemMetrics) GetNetworkBytesIn() int64 {
	if x != nil {
		return x.NetworkBytesIn
	}
	return 0
}

func (x *SystemMetrics) GetNetworkBytesOut() int64 {
	if x != nil {
		return x.NetworkBytesOut
	}
	return 0
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x05agent\"{\n" +
	"\x10ProvisionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x10minecraftVersion\x18\x02 \x01(\tR\x10minecraftVersion\x12'\n" +
	"\aplugins\x18\x03 \x03(\v2\r.agent.PluginR\aplugins\"M\n" +
	"\x11ProvisionResponse\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x13ServerActionRequest\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\"0\n" +
	"\x14ServerActionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"_\n" +
	"\x14UpdatePluginsRequest\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x12'\n" +
	"\aplugins\x18\x02 \x03(\v2\r.agent.PluginR\aplugins\"1\n" +
	"\x15UpdatePluginsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"h\n" +
	"\x14ServerStatusResponse\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"6\n" +
	"\x06Plugin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xb5\x01\n" +
	"\x13RegisterNodeRequest\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12 \n" +
	"\vmemoryBytes\x18\x04 \x01(\x03R\vmemoryBytes\x12\x1a\n" +
	"\bcpuCores\x18\x05 \x01(\x05R\bcpuCores\x12\x1c\n" +
	"\tipAddress\x18\x06 \x01(\tR\tipAddress\"J\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x89\x01\n" +
	"\x10HeartbeatRequest\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12-\n" +
	"\aservers\x18\x02 \x03(\v2\x13.agent.ServerStatusR\aservers\x12.\n" +
	"\ametrics\x18\x03 \x01(\v2\x14.agent.SystemMetricsR\ametrics\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbe\x01\n" +
	"\fServerStatus\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12 \n" +
	"\vplayerCount\x18\x03 \x01(\x05R\vplayerCount\x12\x1a\n" +
	"\bcpuUsage\x18\x04 \x01(\x02R\bcpuUsage\x12 \n" +
	"\vmemoryUsage\x18\x05 \x01(\x03R\vmemoryUsage\x12\x16\n" +
	"\x06uptime\x18\x06 \x01(\x03R\x06uptime\"\xdd\x01\n" +
	"\rSystemMetrics\x12\x1a\n" +
	"\bcpuUsage\x18\x01 \x01(\x02R\bcpuUsage\x12\x1e\n" +
	"\n" +
	"memoryUsed\x18\x02 \x01(\x03R\n" +
	"memoryUsed\x12 \n" +
	"\vmemoryTotal\x18\x03 \x01(\x03R\vmemoryTotal\x12\x1c\n" +
	"\tdiskUsage\x18\x04 \x01(\x02R\tdiskUsage\x12&\n" +
	"\x0enetworkBytesIn\x18\x05 \x01(\x03R\x0enetworkBytesIn\x12(\n" +
	"\x0fnetworkBytesOut\x18\x06 \x01(\x03R\x0fnetworkBytesOut2\xdd\x04\n" +
	"\fAgentService\x12F\n" +
	"\x0fProvisionServer\x12\x17.agent.ProvisionRequest\x1a\x18.agent.ProvisionResponse\"\x00\x12H\n" +
	"\vStartServer\x12\x1a.agent.ServerActionRequest\x1a\x1b.agent.ServerActionResponse\"\x00\x12G\n" +
	"\n" +
	"StopServer\x12\x1a.agent.ServerActionRequest\x1a\x1b.agent.ServerActionResponse\"\x00\x12I\n" +
	"\fDeleteServer\x12\x1a.agent.ServerActionRequest\x1a\x1b.agent.ServerActionResponse\"\x00\x12L\n" +
	"\rUpdatePlugins\x12\x1b.agent.UpdatePluginsRequest\x1a\x1c.agent.UpdatePluginsResponse\"\x00\x12L\n" +
	"\x0fGetServerStatus\x12\x1a.agent.ServerActionRequest\x1a\x1b.agent.ServerStatusResponse\"\x00\x12I\n" +
	"\fRegisterNode\x12\x1a.agent.RegisterNodeRequest\x1a\x1b.agent.RegisterNodeResponse\"\x00\x12@\n" +
	"\tHeartbeat\x12\x17.agent.HeartbeatRequest\x1a\x18.agent.HeartbeatResponse\"\x00B\x13Z\x11mocha-agent/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_agent_proto_goTypes = []any{
	(*ProvisionRequest)(nil),      // 0: agent.ProvisionRequest
	(*ProvisionResponse)(nil),     // 1: agent.ProvisionResponse
	(*ServerActionRequest)(nil),   // 2: agent.ServerActionRequest
	(*ServerActionResponse)(nil),  // 3: agent.ServerActionResponse
	(*UpdatePluginsRequest)(nil),  // 4: agent.UpdatePluginsRequest
	(*UpdatePluginsResponse)(nil), // 5: agent.UpdatePluginsResponse
	(*ServerStatusResponse)(nil),  // 6: agent.ServerStatusResponse
	(*Plugin)(nil),                // 7: agent.Plugin
	(*RegisterNodeRequest)(nil),   // 8: agent.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),  // 9: agent.RegisterNodeResponse
	(*HeartbeatRequest)(nil),      // 10: agent.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 11: agent.HeartbeatResponse
	(*ServerStatus)(nil),          // 12: agent.ServerStatus
	(*SystemMetrics)(nil),         // 13: agent.SystemMetrics
}
var file_proto_agent_proto_depIdxs = []int32{
	7,  // 0: agent.ProvisionRequest.plugins:type_name -> agent.Plugin
	7,  // 1: agent.UpdatePluginsRequest.plugins:type_name -> agent.Plugin
	12, // 2: agent.HeartbeatRequest.servers:type_name -> agent.ServerStatus
	13, // 3: agent.HeartbeatRequest.metrics:type_name -> agent.SystemMetrics
	0,  // 4: agent.AgentService.ProvisionServer:input_type -> agent.ProvisionRequest
	2,  // 5: agent.AgentService.StartServer:input_type -> agent.ServerActionRequest
	2,  // 6: agent.AgentService.StopServer:input_type -> agent.ServerActionRequest
	2,  // 7: agent.AgentService.DeleteServer:input_type -> agent.ServerActionRequest
	4,  // 8: agent.AgentService.UpdatePlugins:input_type -> agent.UpdatePluginsRequest
	2,  // 9: agent.AgentService.GetServerStatus:input_type -> agent.ServerActionRequest
	8,  // 10: agent.AgentService.RegisterNode:input_type -> agent.RegisterNodeRequest
	10, // 11: agent.AgentService.Heartbeat:input_type -> agent.HeartbeatRequest
	1,  // 12: agent.AgentService.ProvisionServer:output_type -> agent.ProvisionResponse
	3,  // 13: agent.AgentService.StartServer:output_type -> agent.ServerActionResponse
	3,  // 14: agent.AgentService.StopServer:output_type -> agent.ServerActionResponse
	3,  // 15: agent.AgentService.DeleteServer:output_type -> agent.ServerActionResponse
	5,  // 16: agent.AgentService.UpdatePlugins:output_type -> agent.UpdatePluginsResponse
	6,  // 17: agent.AgentService.GetServerStatus:output_type -> agent.ServerStatusResponse
	9,  // 18: agent.AgentService.RegisterNode:output_type -> agent.RegisterNodeResponse
	11, // 19: agent.AgentService.Heartbeat:output_type -> agent.HeartbeatResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
