// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plugin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	mi := &file_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugin.ProtoReflect.Descriptor instead.
func (*Plugin) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{0}
}

func (x *Plugin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plugin) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Plugin) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ServerConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServerName         string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerType         string                 `protobuf:"bytes,2,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	MaxPlayers         int32                  `protobuf:"varint,3,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	Difficulty         string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	GameMode           string                 `protobuf:"bytes,5,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	ViewDistance       int32                  `protobuf:"varint,6,opt,name=view_distance,json=viewDistance,proto3" json:"view_distance,omitempty"`
	SpawnProtection    int32                  `protobuf:"varint,7,opt,name=spawn_protection,json=spawnProtection,proto3" json:"spawn_protection,omitempty"`
	Seed               string                 `protobuf:"bytes,8,opt,name=seed,proto3" json:"seed,omitempty"`
	WorldType          string                 `protobuf:"bytes,9,opt,name=world_type,json=worldType,proto3" json:"world_type,omitempty"`
	GenerateStructures bool                   `protobuf:"varint,10,opt,name=generate_structures,json=generateStructures,proto3" json:"generate_structures,omitempty"`
	Memory             int32                  `protobuf:"varint,11,opt,name=memory,proto3" json:"memory,omitempty"`
	Port               int32                  `protobuf:"varint,12,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proto_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerConfig) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

func (x *ServerConfig) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *ServerConfig) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *ServerConfig) GetGameMode() string {
	if x != nil {
		return x.GameMode
	}
	return ""
}

func (x *ServerConfig) GetViewDistance() int32 {
	if x != nil {
		return x.ViewDistance
	}
	return 0
}

func (x *ServerConfig) GetSpawnProtection() int32 {
	if x != nil {
		return x.SpawnProtection
	}
	return 0
}

func (x *ServerConfig) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *ServerConfig) GetWorldType() string {
	if x != nil {
		return x.WorldType
	}
	return ""
}

func (x *ServerConfig) GetGenerateStructures() bool {
	if x != nil {
		return x.GenerateStructures
	}
	return false
}

func (x *ServerConfig) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *ServerConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ProvisionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerId         string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	MinecraftVersion string                 `protobuf:"bytes,2,opt,name=minecraft_version,json=minecraftVersion,proto3" json:"minecraft_version,omitempty"`
	Config           *ServerConfig          `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Plugins          []*Plugin              `protobuf:"bytes,4,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProvisionRequest) Reset() {
	*x = ProvisionRequest{}
	mi := &file_proto_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionRequest) ProtoMessage() {}

func (x *ProvisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionRequest.ProtoReflect.Descriptor instead.
func (*ProvisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *ProvisionRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ProvisionRequest) GetMinecraftVersion() string {
	if x != nil {
		return x.MinecraftVersion
	}
	return ""
}

func (x *ProvisionRequest) GetConfig() *ServerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ProvisionRequest) GetPlugins() []*Plugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type ServerActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ScriptPath    string                 `protobuf:"bytes,2,opt,name=script_path,json=scriptPath,proto3" json:"script_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerActionRequest) Reset() {
	*x = ServerActionRequest{}
	mi := &file_proto_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerActionRequest) ProtoMessage() {}

func (x *ServerActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerActionRequest.ProtoReflect.Descriptor instead.
func (*ServerActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{3}
}

func (x *ServerActionRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ServerActionRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

type ServerActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerActionResponse) Reset() {
	*x = ServerActionResponse{}
	mi := &file_proto_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerActionResponse) ProtoMessage() {}

func (x *ServerActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerActionResponse.ProtoReflect.Descriptor instead.
func (*ServerActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{4}
}

func (x *ServerActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdatePluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Plugins       []*Plugin              `protobuf:"bytes,2,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePluginsRequest) Reset() {
	*x = UpdatePluginsRequest{}
	mi := &file_proto_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePluginsRequest) ProtoMessage() {}

func (x *UpdatePluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePluginsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePluginsRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePluginsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *UpdatePluginsRequest) GetPlugins() []*Plugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type UpdatePluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePluginsResponse) Reset() {
	*x = UpdatePluginsResponse{}
	mi := &file_proto_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePluginsResponse) ProtoMessage() {}

func (x *UpdatePluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePluginsResponse.ProtoReflect.Descriptor instead.
func (*UpdatePluginsResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePluginsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusResponse) Reset() {
	*x = ServerStatusResponse{}
	mi := &file_proto_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusResponse) ProtoMessage() {}

func (x *ServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusResponse.ProtoReflect.Descriptor instead.
func (*ServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{7}
}

func (x *ServerStatusResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ServerStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServerStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_server_proto protoreflect.FileDescriptor

const file_proto_server_proto_rawDesc = "" +
	"\n" +
	"\x12proto/server.proto\x12\x06server\"H\n" +
	"\x06Plugin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x8e\x03\n" +
	"\fServerConfig\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x1f\n" +
	"\vserver_type\x18\x02 \x01(\tR\n" +
	"serverType\x12\x1f\n" +
	"\vmax_players\x18\x03 \x01(\x05R\n" +
	"maxPlayers\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x1b\n" +
	"\tgame_mode\x18\x05 \x01(\tR\bgameMode\x12#\n" +
	"\rview_distance\x18\x06 \x01(\x05R\fviewDistance\x12)\n" +
	"\x10spawn_protection\x18\a \x01(\x05R\x0fspawnProtection\x12\x12\n" +
	"\x04seed\x18\b \x01(\tR\x04seed\x12\x1d\n" +
	"\n" +
	"world_type\x18\t \x01(\tR\tworldType\x12/\n" +
	"\x13generate_structures\x18\n" +
	" \x01(\bR\x12generateStructures\x12\x16\n" +
	"\x06memory\x18\v \x01(\x05R\x06memory\x12\x12\n" +
	"\x04port\x18\f \x01(\x05R\x04port\"\xb4\x01\n" +
	"\x10ProvisionRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12+\n" +
	"\x11minecraft_version\x18\x02 \x01(\tR\x10minecraftVersion\x12,\n" +
	"\x06config\x18\x03 \x01(\v2\x14.server.ServerConfigR\x06config\x12(\n" +
	"\aplugins\x18\x04 \x03(\v2\x0e.server.PluginR\aplugins\"W\n" +
	"\x13ServerActionRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\vscript_path\x18\x02 \x01(\tR\n" +
	"scriptPath\"0\n" +
	"\x14ServerActionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"a\n" +
	"\x14UpdatePluginsRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12(\n" +
	"\aplugins\x18\x02 \x03(\v2\x0e.server.PluginR\aplugins\"1\n" +
	"\x15UpdatePluginsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"i\n" +
	"\x14ServerStatusResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xe0\x03\n" +
	"\rServerManager\x12K\n" +
	"\x0fProvisionServer\x12\x18.server.ProvisionRequest\x1a\x1c.server.ServerActionResponse\"\x00\x12J\n" +
	"\vStartServer\x12\x1b.server.ServerActionRequest\x1a\x1c.server.ServerActionResponse\"\x00\x12I\n" +
	"\n" +
	"StopServer\x12\x1b.server.ServerActionRequest\x1a\x1c.server.ServerActionResponse\"\x00\x12K\n" +
	"\fDeleteServer\x12\x1b.server.ServerActionRequest\x1a\x1c.server.ServerActionResponse\"\x00\x12N\n" +
	"\rUpdatePlugins\x12\x1c.server.UpdatePluginsRequest\x1a\x1d.server.UpdatePluginsResponse\"\x00\x12N\n" +
	"\x0fGetServerStatus\x12\x1b.server.ServerActionRequest\x1a\x1c.server.ServerStatusResponse\"\x00B\x13Z\x11mocha-agent/protob\x06proto3"

var (
	file_proto_server_proto_rawDescOnce sync.Once
	file_proto_server_proto_rawDescData []byte
)

func file_proto_server_proto_rawDescGZIP() []byte {
	file_proto_server_proto_rawDescOnce.Do(func() {
		file_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_server_proto_rawDesc), len(file_proto_server_proto_rawDesc)))
	})
	return file_proto_server_proto_rawDescData
}

var file_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_server_proto_goTypes = []any{
	(*Plugin)(nil),                // 0: server.Plugin
	(*ServerConfig)(nil),          // 1: server.ServerConfig
	(*ProvisionRequest)(nil),      // 2: server.ProvisionRequest
	(*ServerActionRequest)(nil),   // 3: server.ServerActionRequest
	(*ServerActionResponse)(nil),  // 4: server.ServerActionResponse
	(*UpdatePluginsRequest)(nil),  // 5: server.UpdatePluginsRequest
	(*UpdatePluginsResponse)(nil), // 6: server.UpdatePluginsResponse
	(*ServerStatusResponse)(nil),  // 7: server.ServerStatusResponse
}
var file_proto_server_proto_depIdxs = []int32{
	1, // 0: server.ProvisionRequest.config:type_name -> server.ServerConfig
	0, // 1: server.ProvisionRequest.plugins:type_name -> server.Plugin
	0, // 2: server.UpdatePluginsRequest.plugins:type_name -> server.Plugin
	2, // 3: server.ServerManager.ProvisionServer:input_type -> server.ProvisionRequest
	3, // 4: server.ServerManager.StartServer:input_type -> server.ServerActionRequest
	3, // 5: server.ServerManager.StopServer:input_type -> server.ServerActionRequest
	3, // 6: server.ServerManager.DeleteServer:input_type -> server.ServerActionRequest
	5, // 7: server.ServerManager.UpdatePlugins:input_type -> server.UpdatePluginsRequest
	3, // 8: server.ServerManager.GetServerStatus:input_type -> server.ServerActionRequest
	4, // 9: server.ServerManager.ProvisionServer:output_type -> server.ServerActionResponse
	4, // 10: server.ServerManager.StartServer:output_type -> server.ServerActionResponse
	4, // 11: server.ServerManager.StopServer:output_type -> server.ServerActionResponse
	4, // 12: server.ServerManager.DeleteServer:output_type -> server.ServerActionResponse
	6, // 13: server.ServerManager.UpdatePlugins:output_type -> server.UpdatePluginsResponse
	7, // 14: server.ServerManager.GetServerStatus:output_type -> server.ServerStatusResponse
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_server_proto_init() }
func file_proto_server_proto_init() {
	if File_proto_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_server_proto_rawDesc), len(file_proto_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_server_proto_goTypes,
		DependencyIndexes: file_proto_server_proto_depIdxs,
		MessageInfos:      file_proto_server_proto_msgTypes,
	}.Build()
	File_proto_server_proto = out.File
	file_proto_server_proto_goTypes = nil
	file_proto_server_proto_depIdxs = nil
}
